namespace clFish
{
    partial class Form1
    {
        /// <summary>
        ///  Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        ///  Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        ///  Required method for Designer support - do not modify
        ///  the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            this.components = new System.ComponentModel.Container();
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(Form1));
            this.listBox1 = new System.Windows.Forms.ListBox();
            this.button1 = new System.Windows.Forms.Button();
            this.button2 = new System.Windows.Forms.Button();
            this.mainTimer = new System.Windows.Forms.Timer(this.components);
            this.menuStrip1 = new System.Windows.Forms.MenuStrip();
            this.настрокиToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.очиститьЛогToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.button3 = new System.Windows.Forms.Button();
            this.checkBox1 = new System.Windows.Forms.CheckBox();
            this.chTimer = new System.Windows.Forms.Timer(this.components);
            this.statusStrip1 = new System.Windows.Forms.StatusStrip();
            this.toolStripStatusLabel1 = new System.Windows.Forms.ToolStripStatusLabel();
            this.toolStripStatusLabel5 = new System.Windows.Forms.ToolStripStatusLabel();
            this.toolStripStatusLabel3 = new System.Windows.Forms.ToolStripStatusLabel();
            this.toolStripStatusLabel6 = new System.Windows.Forms.ToolStripStatusLabel();
            this.toolStripStatusLabel2 = new System.Windows.Forms.ToolStripStatusLabel();
            this.toolStripStatusLabel7 = new System.Windows.Forms.ToolStripStatusLabel();
            this.toolStripStatusLabel4 = new System.Windows.Forms.ToolStripStatusLabel();
            this.tabControl1 = new System.Windows.Forms.TabControl();
            this.tabPage1 = new System.Windows.Forms.TabPage();
            this.pictureBox1 = new System.Windows.Forms.PictureBox();
            this.lstTargets = new System.Windows.Forms.ListBox();
            this.button4 = new System.Windows.Forms.Button();
            this.checkBox2 = new System.Windows.Forms.CheckBox();
            this.textBox1 = new System.Windows.Forms.TextBox();
            this.listBox3 = new System.Windows.Forms.ListBox();
            this.listBox2 = new System.Windows.Forms.ListBox();
            this.label2 = new System.Windows.Forms.Label();
            this.label1 = new System.Windows.Forms.Label();
            this.comboBox2 = new System.Windows.Forms.ComboBox();
            this.comboBox1 = new System.Windows.Forms.ComboBox();
            this.tabPage2 = new System.Windows.Forms.TabPage();
            this.menuStrip1.SuspendLayout();
            this.statusStrip1.SuspendLayout();
            this.tabControl1.SuspendLayout();
            this.tabPage1.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.pictureBox1)).BeginInit();
            this.SuspendLayout();
            // 
            // listBox1
            // 
            this.listBox1.BackColor = System.Drawing.Color.DarkSlateBlue;
            this.listBox1.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
            this.listBox1.ForeColor = System.Drawing.SystemColors.Info;
            this.listBox1.FormattingEnabled = true;
            this.listBox1.ItemHeight = 17;
            this.listBox1.Location = new System.Drawing.Point(6, 386);
            this.listBox1.Name = "listBox1";
            this.listBox1.Size = new System.Drawing.Size(460, 274);
            this.listBox1.TabIndex = 0;
            // 
            // button1
            // 
            this.button1.Location = new System.Drawing.Point(6, 666);
            this.button1.Name = "button1";
            this.button1.Size = new System.Drawing.Size(57, 26);
            this.button1.TabIndex = 1;
            this.button1.Text = "Старт";
            this.button1.UseVisualStyleBackColor = true;
            this.button1.Click += new System.EventHandler(this.button1_Click);
            // 
            // button2
            // 
            this.button2.Location = new System.Drawing.Point(410, 665);
            this.button2.Name = "button2";
            this.button2.Size = new System.Drawing.Size(56, 27);
            this.button2.TabIndex = 2;
            this.button2.Text = "Стоп";
            this.button2.UseVisualStyleBackColor = true;
            this.button2.Click += new System.EventHandler(this.button2_Click);
            // 
            // mainTimer
            // 
            this.mainTimer.Interval = 600;
            this.mainTimer.Tick += new System.EventHandler(this.mainTimer_Tick);
            // 
            // menuStrip1
            // 
            this.menuStrip1.Items.AddRange(new System.Windows.Forms.ToolStripItem[] {
            this.настрокиToolStripMenuItem});
            this.menuStrip1.Location = new System.Drawing.Point(0, 0);
            this.menuStrip1.Name = "menuStrip1";
            this.menuStrip1.Size = new System.Drawing.Size(472, 25);
            this.menuStrip1.TabIndex = 4;
            this.menuStrip1.Text = "menuStrip1";
            // 
            // настрокиToolStripMenuItem
            // 
            this.настрокиToolStripMenuItem.DropDownItems.AddRange(new System.Windows.Forms.ToolStripItem[] {
            this.очиститьЛогToolStripMenuItem});
            this.настрокиToolStripMenuItem.Name = "настрокиToolStripMenuItem";
            this.настрокиToolStripMenuItem.Size = new System.Drawing.Size(76, 21);
            this.настрокиToolStripMenuItem.Text = "Настроки";
            // 
            // очиститьЛогToolStripMenuItem
            // 
            this.очиститьЛогToolStripMenuItem.Name = "очиститьЛогToolStripMenuItem";
            this.очиститьЛогToolStripMenuItem.Size = new System.Drawing.Size(154, 22);
            this.очиститьЛогToolStripMenuItem.Text = "Очистить лог";
            this.очиститьЛогToolStripMenuItem.Click += new System.EventHandler(this.очиститьЛогToolStripMenuItem_Click);
            // 
            // button3
            // 
            this.button3.Location = new System.Drawing.Point(402, 35);
            this.button3.Name = "button3";
            this.button3.Size = new System.Drawing.Size(58, 32);
            this.button3.TabIndex = 5;
            this.button3.Text = "Пуск";
            this.button3.UseVisualStyleBackColor = true;
            this.button3.Click += new System.EventHandler(this.button3_Click);
            // 
            // checkBox1
            // 
            this.checkBox1.AutoSize = true;
            this.checkBox1.BackColor = System.Drawing.SystemColors.AppWorkspace;
            this.checkBox1.Location = new System.Drawing.Point(12, 35);
            this.checkBox1.Name = "checkBox1";
            this.checkBox1.Size = new System.Drawing.Size(88, 21);
            this.checkBox1.TabIndex = 6;
            this.checkBox1.Text = "Закрепить";
            this.checkBox1.UseVisualStyleBackColor = false;
            // 
            // chTimer
            // 
            this.chTimer.Enabled = true;
            this.chTimer.Interval = 500;
            this.chTimer.Tick += new System.EventHandler(this.chTimer_Tick);
            // 
            // statusStrip1
            // 
            this.statusStrip1.Items.AddRange(new System.Windows.Forms.ToolStripItem[] {
            this.toolStripStatusLabel1,
            this.toolStripStatusLabel5,
            this.toolStripStatusLabel3,
            this.toolStripStatusLabel6,
            this.toolStripStatusLabel2,
            this.toolStripStatusLabel7,
            this.toolStripStatusLabel4});
            this.statusStrip1.Location = new System.Drawing.Point(0, 695);
            this.statusStrip1.Name = "statusStrip1";
            this.statusStrip1.Size = new System.Drawing.Size(472, 22);
            this.statusStrip1.TabIndex = 7;
            this.statusStrip1.Text = "statusStrip1";
            // 
            // toolStripStatusLabel1
            // 
            this.toolStripStatusLabel1.BorderStyle = System.Windows.Forms.Border3DStyle.Sunken;
            this.toolStripStatusLabel1.Margin = new System.Windows.Forms.Padding(65, 3, 0, 2);
            this.toolStripStatusLabel1.Name = "toolStripStatusLabel1";
            this.toolStripStatusLabel1.Size = new System.Drawing.Size(55, 17);
            this.toolStripStatusLabel1.Text = "Всего: 0";
            // 
            // toolStripStatusLabel5
            // 
            this.toolStripStatusLabel5.Name = "toolStripStatusLabel5";
            this.toolStripStatusLabel5.Size = new System.Drawing.Size(27, 17);
            this.toolStripStatusLabel5.Text = "  |  ";
            // 
            // toolStripStatusLabel3
            // 
            this.toolStripStatusLabel3.Name = "toolStripStatusLabel3";
            this.toolStripStatusLabel3.Size = new System.Drawing.Size(70, 17);
            this.toolStripStatusLabel3.Text = "Мелочь: 0";
            // 
            // toolStripStatusLabel6
            // 
            this.toolStripStatusLabel6.Name = "toolStripStatusLabel6";
            this.toolStripStatusLabel6.Size = new System.Drawing.Size(27, 17);
            this.toolStripStatusLabel6.Text = "  |  ";
            // 
            // toolStripStatusLabel2
            // 
            this.toolStripStatusLabel2.Name = "toolStripStatusLabel2";
            this.toolStripStatusLabel2.Size = new System.Drawing.Size(70, 17);
            this.toolStripStatusLabel2.Text = "Зачётов: 0";
            // 
            // toolStripStatusLabel7
            // 
            this.toolStripStatusLabel7.Name = "toolStripStatusLabel7";
            this.toolStripStatusLabel7.Size = new System.Drawing.Size(27, 17);
            this.toolStripStatusLabel7.Text = "  |  ";
            // 
            // toolStripStatusLabel4
            // 
            this.toolStripStatusLabel4.Name = "toolStripStatusLabel4";
            this.toolStripStatusLabel4.Size = new System.Drawing.Size(47, 17);
            this.toolStripStatusLabel4.Text = "Max: 0";
            // 
            // tabControl1
            // 
            this.tabControl1.Controls.Add(this.tabPage1);
            this.tabControl1.Controls.Add(this.tabPage2);
            this.tabControl1.Location = new System.Drawing.Point(6, 65);
            this.tabControl1.Name = "tabControl1";
            this.tabControl1.SelectedIndex = 0;
            this.tabControl1.Size = new System.Drawing.Size(460, 315);
            this.tabControl1.TabIndex = 8;
            // 
            // tabPage1
            // 
            this.tabPage1.Controls.Add(this.pictureBox1);
            this.tabPage1.Controls.Add(this.lstTargets);
            this.tabPage1.Controls.Add(this.button4);
            this.tabPage1.Controls.Add(this.checkBox2);
            this.tabPage1.Controls.Add(this.textBox1);
            this.tabPage1.Controls.Add(this.listBox3);
            this.tabPage1.Controls.Add(this.listBox2);
            this.tabPage1.Controls.Add(this.label2);
            this.tabPage1.Controls.Add(this.label1);
            this.tabPage1.Controls.Add(this.comboBox2);
            this.tabPage1.Controls.Add(this.comboBox1);
            this.tabPage1.Location = new System.Drawing.Point(4, 26);
            this.tabPage1.Name = "tabPage1";
            this.tabPage1.Padding = new System.Windows.Forms.Padding(3);
            this.tabPage1.Size = new System.Drawing.Size(452, 285);
            this.tabPage1.TabIndex = 0;
            this.tabPage1.Text = "Близнецы";
            this.tabPage1.UseVisualStyleBackColor = true;
            // 
            // pictureBox1
            // 
            this.pictureBox1.Image = ((System.Drawing.Image)(resources.GetObject("pictureBox1.Image")));
            this.pictureBox1.Location = new System.Drawing.Point(80, 207);
            this.pictureBox1.Name = "pictureBox1";
            this.pictureBox1.Size = new System.Drawing.Size(57, 72);
            this.pictureBox1.SizeMode = System.Windows.Forms.PictureBoxSizeMode.AutoSize;
            this.pictureBox1.TabIndex = 15;
            this.pictureBox1.TabStop = false;
            this.pictureBox1.Visible = false;
            // 
            // lstTargets
            // 
            this.lstTargets.BackColor = System.Drawing.SystemColors.InfoText;
            this.lstTargets.ForeColor = System.Drawing.Color.OrangeRed;
            this.lstTargets.FormattingEnabled = true;
            this.lstTargets.ItemHeight = 17;
            this.lstTargets.Location = new System.Drawing.Point(226, 207);
            this.lstTargets.Name = "lstTargets";
            this.lstTargets.Size = new System.Drawing.Size(220, 89);
            this.lstTargets.TabIndex = 14;
            // 
            // button4
            // 
            this.button4.Location = new System.Drawing.Point(6, 212);
            this.button4.Name = "button4";
            this.button4.Size = new System.Drawing.Size(47, 31);
            this.button4.TabIndex = 13;
            this.button4.Text = "Найти";
            this.button4.UseVisualStyleBackColor = true;
            this.button4.Visible = false;
            this.button4.Click += new System.EventHandler(this.button4_Click);
            // 
            // checkBox2
            // 
            this.checkBox2.AutoSize = true;
            this.checkBox2.Location = new System.Drawing.Point(343, 3);
            this.checkBox2.Name = "checkBox2";
            this.checkBox2.Size = new System.Drawing.Size(104, 21);
            this.checkBox2.TabIndex = 11;
            this.checkBox2.Text = "Отслеживать";
            this.checkBox2.UseVisualStyleBackColor = true;
            // 
            // textBox1
            // 
            this.textBox1.Location = new System.Drawing.Point(6, 69);
            this.textBox1.Name = "textBox1";
            this.textBox1.PlaceholderText = "Минимальный вес в граммах";
            this.textBox1.Size = new System.Drawing.Size(440, 25);
            this.textBox1.TabIndex = 10;
            // 
            // listBox3
            // 
            this.listBox3.BackColor = System.Drawing.SystemColors.Desktop;
            this.listBox3.ForeColor = System.Drawing.SystemColors.Info;
            this.listBox3.FormattingEnabled = true;
            this.listBox3.ItemHeight = 17;
            this.listBox3.Location = new System.Drawing.Point(226, 100);
            this.listBox3.Name = "listBox3";
            this.listBox3.Size = new System.Drawing.Size(220, 106);
            this.listBox3.TabIndex = 5;
            // 
            // listBox2
            // 
            this.listBox2.BackColor = System.Drawing.SystemColors.Desktop;
            this.listBox2.ForeColor = System.Drawing.SystemColors.Info;
            this.listBox2.FormattingEnabled = true;
            this.listBox2.ItemHeight = 17;
            this.listBox2.Location = new System.Drawing.Point(6, 100);
            this.listBox2.Name = "listBox2";
            this.listBox2.Size = new System.Drawing.Size(220, 106);
            this.listBox2.TabIndex = 4;
            // 
            // label2
            // 
            this.label2.AutoSize = true;
            this.label2.Location = new System.Drawing.Point(230, 16);
            this.label2.Name = "label2";
            this.label2.Size = new System.Drawing.Size(50, 17);
            this.label2.TabIndex = 3;
            this.label2.Text = "Рыба 2";
            // 
            // label1
            // 
            this.label1.AutoSize = true;
            this.label1.Location = new System.Drawing.Point(8, 16);
            this.label1.Name = "label1";
            this.label1.Size = new System.Drawing.Size(50, 17);
            this.label1.TabIndex = 2;
            this.label1.Text = "Рыба 1";
            // 
            // comboBox2
            // 
            this.comboBox2.FormattingEnabled = true;
            this.comboBox2.Items.AddRange(new object[] {
            "*",
            "Абрамитес мраморный",
            "Австралийский анчоус",
            "Австралийский колючепер",
            "Австралийский шишечник",
            "Адамуссиус",
            "Адский вампир",
            "Азиатская зубатка",
            "Акара голубовато-пятнистая",
            "Акарихтис Хекеля",
            "Алект вымпельный",
            "Акула",
            "Акула американская кунья",
            "Акула большеносая",
            "Акула гладкозубая",
            "Акула мадагаскарская",
            "Акула пелагическая лисья",
            "Акула пилозубая",
            "Акула темная",
            "Акула шелковая",
            "Акула-Небрия",
            "Акула-нянька короткохвостая",
            "Акула-собака",
            "Акула азиатская кунья",
            "Акула белая",
            "Акула белоглазая",
            "Акула белоперая",
            "Акула галапагосская",
            "Акула гигантская",
            "Акула гренландская",
            "Акула длиннокрылая",
            "Акула звездчатошипая",
            "Акула зебровая",
            "Акула индонезийская",
            "Акула карибская длиннорылая",
            "Акулка карликовая",
            "Акула китовая",
            "Акула мальгашская",
            "Акула мелкозубая",
            "Акула ночная",
            "Акула острозубая песчаная",
            "Акула Оустона",
            "Акула пепельная",
            "Акула плоскоголовая",
            "Акула рифовая",
            "Акула Сейла",
            "Акула свиноглазая",
            "Акула серо-бурая",
            "Акула серо-голубая",
            "Акула суповая",
            "Акула темноперая",
            "Акула тигровая",
            "Акула узкозубая",
            "Акула флоридская",
            "Акула черноперая",
            "Акула шестижаберная",
            "Акула-бык",
            "Акула-лисица",
            "Акула-молот обыкновенная",
            "Акула-нянька усатая",
            "Акула японская бычья",
            "Алеста",
            "Альбула",
            "Ампуллярия",
            "Американский угорь",
            "Амфихт",
            "Амурская Щука",
            "Амурский Осетр",
            "Амурский Сиг",
            "Анаконда",
            "Ангел лирохвостый",
            "Ангел черноплавничный",
            "Апистограммова факельная",
            "Апсил зубатый",
            "Аравана серебристая",
            "Аравана черная",
            "Арапаима",
            "Аристохромис Кристи",
            "Аротрон белоточечный",
            "Аррип большой",
            "Аррип малый",
            "Аспатария марнои",
            "Аспатария пифлоидная",
            "Астронотус глаздчатый",
            "Атлантический Осетр",
            "Аротрон колючий",
            "Архитеутис",
            "Аулонокара Бенша",
            "Аулонокара Ньяса",
            "Аухеногланис",
            "Ауха",
            "Бабочка малавийская",
            "Багре гури",
            "Багре негро",
            "Байкальский осетр",
            "Барабулька",
            "Барамунди",
            "Барракуда",
            "Барракуда тупорылая",
            "Башир",
            "Баяд",
            "Белоглазка",
            "Белуга",
            "Белуга черноморская",
            "Белуха",
            "Бельдюга восточная",
            "Белый амур",
            "Берикс австралийский",
            "Берш",
            "Бестер",
            "Биара",
            "Бикуда",
            "Бисса",
            "Болотная черепаха",
            "Большая сериола",
            "Большеротый окунь",
            "Большой каранкс",
            "Бонито",
            "Бородавчатка",
            "Бородавчатка красноморская",
            "Бронзовая акула",
            "Бротула многоусая",
            "Брызгун крупнопятнистый",
            "Букцинум",
            "Буртония Фоаи",
            "Бутылконос плоскоголовый",
            "Бутылконос северный",
            "Буффало большеротый",
            "Буффало малоротый",
            "Буффало черный",
            "Быстрянка",
            "Бычеглаз-хамрур",
            "Бычерыл американский",
            "Бычок",
            "Бычок-кнут",
            "Бычок краснозубый",
            "Бычок-цуцик",
            "Валаамка",
            "Валек",
            "Вариола белокаемчатая",
            "Ваху",
            "Венера воздушная",
            "Верхогляд",
            "Веслонос",
            "Владиславия",
            "Вобла",
            "Волосозуб",
            "Волютопсиус каштановый",
            "Ворчун крапчатый",
            "Восточная треска",
            "Восточносибирский хариус",
            "Вунду",
            "Вырезуб",
            "Вьюн",
            "Галаксия пятнистая",
            "Галаксия Тасманская",
            "Гаррупа-мармита",
            "Гетеротис",
            "Гигантская акула-молот",
            "Гигантский головастик",
            "Гигантский карп",
            "Гидромедуза бразильская",
            "Гимносарда",
            "Гипоплектрус",
            "Гитарный скат",
            "Глаукус",
            "Глицимерис приморский",
            "Глосса",
            "Глубинная щука",
            "Глубинный судак",
            "Голавль",
            "Голец альпийский",
            "Голец арктический",
            "Голец длинноголовый",
            "Голец-кристивомер",
            "Голец Леванидова",
            "Голец носатый",
            "Голец Таранца",
            "Голец усатый",
            "Голец Черского",
            "Голомянка",
            "Голубая акула",
            "Голубая линкия",
            "Голубой марлин",
            "Голубой тунец",
            "Голый осман",
            "Гольян Лаговского",
            "Гольян Чекановского",
            "Гонатус",
            "Горбуша",
            "Горбуша южноамериканская",
            "Горбыль",
            "Гребешок бело-розовый",
            "Гребешок исландский",
            "Гребешок коралловый",
            "Грамма королевская",
            "Гребешок лунный",
            "Гребешок раскрашенный",
            "Гребешок Свифта",
            "Гребнистый крокодил",
            "Гребешок многообразный",
            "Гринда обыкновенная",
            "Греческий сосуд",
            "Гринда короткоплавниковая",
            "Группер Квинслендский",
            "Группер красноротый",
            "Группер таувина",
            "Группер буропятнистый",
            "Группер желто-синий",
            "Группер индоокеанский малоглазый",
            "Группер крупнопятнистый",
            "Группер палевый",
            "Группер темный",
            "Группер шестиполосый",
            "Гуативера",
            "Гуачанчо",
            "Губан гребенчатый",
            "Губан колючий",
            "Губан носатый",
            "Губан пятнистый",
            "Губан радужный",
            "Густера",
            "Даватчан",
            "Даллия",
            "Дасцилл зебровидный",
            "Двухцветная пеламида",
            "Джакунда",
            "Дианема полосатохвостая",
            "Дискус зеленый",
            "Дискус Хеккеля",
            "Дистиходус шестиполосый",
            "Длиннопалый рак",
            "Длинноперый тунец",
            "Длиннорылый полурыл",
            "Долгопер средиземноморский",
            "Дорадо",
            "Дрейссена речная",
            "Дунайский пузанок",
            "Евдошка европейская",
            "Евдошка американская",
            "Единорог расписной",
            "Елец",
            "Елец-андруга",
            "Елец Сибирский",
            "Ерш",
            "Ерш носарь",
            "Ершоватка",
            "Желтокрылка",
            "Желтопёрый тунец",
            "Желтохвост",
            "Желтощек",
            "Жерех",
            "Жерех-лысач",
            "Зайцеголовый терпуг",
            "Запрора",
            "Звезда-подушка",
            "Звездочет крапчатый",
            "Зебровый хирург",
            "Зеленушка",
            "Зеленый луциан",
            "Змееголов",
            "Змеиная макрель",
            "Золотистая сериола",
            "Золотистая скорпена",
            "Золотистый линь",
            "Золотой леопард",
            "Зубатка дальневосточная",
            "Зубатка полосатая",
            "Зубатка пятнистая",
            "Зубатка синяя",
            "Зубарик обыкновенный",
            "Иглобрюх-попугайчик",
            "Идол мавританский",
            "Императорский ангел",
            "Инанга",
            "Иния",
            "Кабра-мора",
            "Кабрилья",
            "Кабуча",
            "Кайман гладколобый",
            "Кайман крокодиловый",
            "Кайман черный",
            "Калинка",
            "Каллиста короткосифонная",
            "Каллитака Адамса",
            "Каллихт",
            "Калуга",
            "Кальмар гигантский",
            "Кальмар командорский",
            "Кальмар обыкновенный",
            "Кальмар тихоокеанский",
            "Камбала двухлинейная",
            "Камбала звёздчатая",
            "Камбала зеленая",
            "Камбала кесслера",
            "Камбала морская",
            "Камнеточец",
            "Камчатский краб",
            "Каракатица лечебная",
            "Каракатица расписная",
            "Кальвус",
            "Камерония Бургинья",
            "Кампанго",
            "Каранкс черный",
            "Каранг золотой",
            "Карась золотой",
            "Карась серебряный",
            "Карась морской",
            "Карась морской чернополосый",
            "Карась-барабан",
            "Кардиум реснитчатый",
            "Карп",
            "Карп африканский",
            "Карп голый",
            "Карп зеркальный",
            "Карп индийский",
            "Картофельный группер",
            "Катран",
            "Каури-монета",
            "Кашалот",
            "Кашалот карликовый",
            "Кашорро краснохвостый",
            "Керчак-яок",
            "Кета",
            "Кефаль алмазная",
            "Кефаль-губач",
            "Кефаль-лобан",
            "Кижуч",
            "Кижуч южноамериканский",
            "Кит горбатый",
            "Кит карликовый",
            "Кит серый",
            "Кит синий",
            "Кит японский",
            "Кит бискайский",
            "Китовая акула",
            "Клоун танганьикский",
            "Клюворыл",
            "Коаро",
            "Кобия",
            "Комета",
            "Конголли",
            "Конус дворцовый",
            "Конус географический",
            "Конус письменный",
            "Конус полосатый",
            "Конус текстильный",
            "Кожистая черепаха",
            "Кокани",
            "Колоссома",
            "Колючий краб",
            "Колюшка девятииглая",
            "Колюшка трехиглая",
            "Копьеносец малый",
            "Коралловый группер",
            "Корифена малая",
            "Королевский луциан",
            "Корюшка",
            "Корюшка озерная малоротая",
            "Косатка",
            "Коелатура мозамбикская",
            "Королева Ньяса",
            "Королева Танганьики",
            "Кохаку",
            "Кошачья акула",
            "Краб вельветовый",
            "Краб королевский",
            "Краб красный мангровый",
            "Краб Мраморный",
            "Краб сине-красный",
            "Краб снежный",
            "Краб съедобный",
            "Краб малавийский голубой",
            "Краб монтивагус",
            "Краб танганьикский",
            "Краппи белый",
            "Красное бревно",
            "Красноперка",
            "Красный конгрио",
            "Красный луциан",
            "Креветка северная",
            "Крокодил Джонстона",
            "Крокодил нильский",
            "Крокодил узкорылый",
            "Крупночешуйчатый угай",
            "Крылатка-зебра",
            "Крылатка антенновая",
            "Кряжевая палия",
            "Кубера",
            "Кудрепер Форстера",
            "Кузовок-кубик",
            "Кузовок рогатый",
            "Кумжа",
            "Кумжа южноамериканская",
            "Кунджа",
            "Кутум",
            "Кэтфиш",
            "Лабеотрофеус обыкновенный",
            "Лабидохромис большой",
            "Лабидохромис Хонги",
            "Лаванда Мбуна",
            "Лабынкырская мальма",
            "Лабынкырский хариус",
            "Лабынкырский чёрт",
            "Лаврак",
            "Лаврак белый",
            "Лаврак полосатый",
            "Ламна",
            "Ледяная рыба",
            "Лемонема",
            "Ленок",
            "Ленский пескарь",
            "Ленский хариус",
            "Леопардовый группер",
            "Лепоринус зебровый",
            "Лепоринус фредерика",
            "Летрин длиннорылый",
            "Летрин небесный",
            "Лещ",
            "Лещ Восточносибирский",
            "Лещ морской белый",
            "Лещ морской кинжальный",
            "Лещ морской",
            "Лещ черный южный",
            "Ликодонт яванский",
            "Лиманда длиннорылая",
            "Лиманда желтохвостая",
            "Линь",
            "Логгерхед",
            "Лососевая акула",
            "Лосось",
            "Лосось дунайский",
            "Лосось Каспийский",
            "Лосось Кларка",
            "Лосось южноамериканский",
            "Лоцман",
            "Луварь",
            "Лудога",
            "Лудожная палия",
            "Лунник",
            "Луфарь",
            "Луциан Бохар",
            "Луциан горбатый",
            "Лягушка",
            "Лягушка нильская",
            "Лягушка роющая",
            "Лямбис подагрический",
            "Мавританский клоун",
            "Мазутный двухголов",
            "Макома широкая",
            "Макрель бразильская",
            "Макрель голубая",
            "Мако длинноплавниковый",
            "Макрель западноатлантическая",
            "Макруронус новозеландский",
            "Макрель-Кавалла",
            "Мактра китайская",
            "Мактра сахалинская",
            "Мактромерис изменчивый",
            "Малабарский хоплиас",
            "Малоглазый макрурус",
            "Малый полосатик",
            "Мальма",
            "Мангровый джек",
            "Мандаринка",
            "Манта",
            "Марлин атлантический",
            "Масляная рыба",
            "Мбамба",
            "Мбенга",
            "Меланохромис",
            "Мелания песчаная",
            "Мелкозубый пилорыл",
            "Мелкочешуйчатый краснопер",
            "Мелкочешуйчатый угай",
            "Мена пятнистая",
            "Менёк",
            "Мерланг",
            "Мероу красный",
            "Метиннис пятнистый",
            "Мидия",
            "Микижа",
            "Микижа чилийская",
            "Миксина атлантическая",
            "Милеус ленточный",
            "Милоссома килебрюхая",
            "Минтай",
            "Минога морская",
            "Минога огайская",
            "Многопёр Эндлихера",
            "Мормир бутылконосый",
            "Моллюск",
            "Монгольский краснопер",
            "Мормиропс угревидный",
            "Морская звезда красношипая",
            "Мойва",
            "Мольва",
            "Морская лисица",
            "Морская свинья Далля",
            "Морская свинья тихоокеанская",
            "Морская собачка",
            "Морской ворон",
            "Морской еж",
            "Морской орел",
            "Морской финик",
            "Морской черт",
            "Моторо",
            "Мригал",
            "Мускулус",
            "Муксун",
            "Мурджан",
            "Мурена гигантская",
            "Мурена перечная",
            "Муреная ячеистая",
            "Мурена европейская",
            "Мурена желторотая",
            "Мурена ленточная",
            "Мурена-зебра",
            "Мутела",
            "Мухтельский карась",
            "Налим",
            "Налим средиземноморский",
            "Нанностом Бекфорда",
            "Неалот",
            "Нейва",
            "Нельма",
            "Необерингиус Фрилея",
            "Нереис",
            "Нерка",
            "Нерка карликовая",
            "Нерпа байкальская",
            "Нильский окунь",
            "Нимбохромис полистигма",
            "Нодулария боеми",
            "Носорог безрогий",
            "Носорог однорогий",
            "Новозеландская мерлуза",
            "Носатая энгидрина",
            "Обыкновенный краб-стригун",
            "Озерная форель",
            "Озерный гольян",
            "Окунь",
            "Окунь алеутский",
            "Окунь большеглазый",
            "Окунь вилохвостый",
            "Окунь гладкий",
            "Окунь танганьикский",
            "Окунь золотой",
            "Окунь малый",
            "Окунь северный морской",
            "Окунь каменный",
            "Окунь красноглазый",
            "Окунь малоротый",
            "Окунь морской золотистый",
            "Окунь морской норвежский",
            "Окунь песчаный",
            "Окунь прибрежный",
            "Окунь пятнистый",
            "Окунь ушастый",
            "Окунь-клювач",
            "Окунь-пират",
            "Омар голубой",
            "Омар европейский",
            "Омар норвежский",
            "Омуль",
            "Омуль Байкальский",
            "Омуль маломорский",
            "Омуль посольский",
            "Омуль северобайкальский",
            "Омуль селенгинский",
            "Омуль чивыркуйский",
            "Оникия",
            "Ореохромис Каронга",
            "Оренжи Огон",
            "Орфа",
            "Ореховидка тонкая",
            "Осетр",
            "Осетр тупорылый",
            "Осетр Восточносибирский",
            "Острорылый крокодил",
            "Острорылый ленок",
            "Осьминог обыкновенный",
            "Осьминог семирукий",
            "Офиура полосатая",
            "Офтальмотиляпия носатая",
            "Павлиний группер",
            "Павлиний окунь-бабочка",
            "Павлиний окунь ленточный",
            "Пагелл красный",
            "Пагр красный",
            "Пака",
            "Палия",
            "Палия американская",
            "Палия южноамериканская",
            "Палтус атлантический",
            "Палтус Белокорый",
            "Палтус синекорый",
            "Палтус стрелозубый",
            "Пальмовый вор",
            "Панцирник длиннорылый",
            "Панцирник миссисипский",
            "Парусник",
            "Патагонский гребешок",
            "Патагонский клыкач",
            "Патагонский лобстер",
            "Пеламида атлантическая",
            "Пеленгас",
            "Пелядь",
            "Пенжинский омуль",
            "Переславская ряпушка",
            "Перечный слизняк",
            "Перка",
            "Перонидия жилковатая",
            "Персидский осетр",
            "Перуанский анчоус",
            "Перуанская макрель",
            "Перуанская сардина",
            "Перуанская сериолелла",
            "Перуанская ставрида",
            "Пескарь",
            "Пестрый конь",
            "Пестрый толстолобик",
            "Петушок",
            "Пигоплит",
            "Пикша",
            "Пинагор",
            "Пираиба",
            "Пиракатинга",
            "Пиранья вымпельная",
            "Пиранья краснобрюхая",
            "Пиранья обыкновенная",
            "Пиранья ромбовидная",
            "Пиранья стройная",
            "Пирапитинга",
            "Пирапутанга",
            "Пираруку",
            "Пиратский клад",
            "Платакс-нетопырь",
            "Плоскоголов бахромчатый",
            "Платинум Огон",
            "Плоскоголов пятнистый",
            "Плотва",
            "Подкаменщик",
            "Подлещик",
            "Подуст",
            "Полиптер",
            "Поллак",
            "Поллимир Исидора",
            "Полосатая камбала",
            "Полосатик Брайда",
            "Полосатик Идена",
            "Полосатик карликовый",
            "Полосатик южный",
            "Полосатый марлин",
            "Полярная акула",
            "Помакант рябой",
            "Попока",
            "Пресноводный краб",
            "Принцесса Бурунди",
            "Протоптер бурый",
            "Протоптер малый",
            "Приморский гребешок",
            "Промикропс",
            "Протоптер мраморный",
            "Прудовик",
            "Псевдотрофеус Демасони",
            "Птеригоплихт парчовый",
            "Пузанок",
            "Пустая бочка",
            "Путассу северная",
            "Пыжьян",
            "Пятиугольный волосатый краб",
            "Пятнистая озерная лягушка",
            "Пятнистый воббегонг",
            "Пятнистый рак",
            "Пятнистый сладкогуб",
            "Радужная вариола",
            "Радужная форель",
            "Рак",
            "Рак красный флоридский",
            "Рак сигнальный",
            "Рапана",
            "Рапана венозная",
            "Рваный сапог",
            "Ремнезуб атлантический",
            "Ремнезуб Грея",
            "Ремнезуб Блэнвиля",
            "Рипус",
            "Робало",
            "Рогатка",
            "Розовый луциан",
            "Ротан",
            "Ручьевая форель",
            "Рыба лира",
            "Рыба меч",
            "Рыба-бекас",
            "Рыба-белка",
            "Рыба-еж длинношипая",
            "Рыба-лиса",
            "Рыба-луна",
            "Рыба-лягушка",
            "Рыба-Наполеон",
            "Рыба-ремень",
            "Рыбальдо",
            "Рыбец",
            "Ряпушка",
            "Сазан",
            "Сайда",
            "Сайка",
            "Сайра атлантическая",
            "Саратога",
            "Сарган",
            "Сарган крокодиловый",
            "Сардина танганьикская",
            "Сардина европейская",
            "Сахалинская лиманда",
            "Сахалинский осетр",
            "Свинья аргентинская",
            "Свистулька голубопятнистая",
            "Сева",
            "Севанская форель",
            "Северный клювач",
            "Севрюга",
            "Сейвал",
            "Селар",
            "Сельдь американская",
            "Сельдь Каспийская",
            "Семга",
            "Семга камчатская",
            "Семутунду",
            "Сердцевидка съедобная",
            "Сердеронг чернопятнистый",
            "Серое бревно",
            "Серрипес замечательный",
            "Серцевидка",
            "Сиб.голец-усач",
            "Сибирская ряпушка",
            "Сибирский подкаменщик",
            "Сиг",
            "Сиг-востряк",
            "Сиг-Xадары",
            "Сиган звездчатый",
            "Сиган струйчатый",
            "Сиган яванский",
            "Сима",
            "Сима южноамериканская",
            "Синекольчатый осьминог",
            "Синеплавниковый каранкс",
            "Синеполосый луциан",
            "Синец",
            "Скалозуб бурый",
            "Скватина американская",
            "Скалярия леопольда",
            "Скар двухцветный",
            "Скар рубиновый",
            "Скар широколобый",
            "Скат",
            "Скат пятнистый",
            "Скат-орляк белоточечный",
            "Скат-орляк изысканный",
            "Скат акулий",
            "Скат колючий",
            "Скат мозаичный",
            "Скат Йенсена",
            "Скат короткохвостый",
            "Скат круглый",
            "Скат лучевой",
            "Скат Монтегю",
            "Скат полярный",
            "Скат тэниура лимма",
            "Скат-орляк пятнистый",
            "Скат-торпедо электрический",
            "Скат-орляк австралийский",
            "Сладкогуб гигантский",
            "Скорпенопсис дьявольский",
            "Скрипун",
            "Скумбрия атлантическая",
            "Снэппер низкотелый",
            "Снэппер нитеперый",
            "Собачка речная",
            "Солидус",
            "Солнечник обыкновенный",
            "Солнечник синежаберный",
            "Сом",
            "Сом Амурский",
            "Сом жирафовый",
            "Сом малавийский",
            "Сом мраморный",
            "Сом танганьикский",
            "Сом ширентис",
            "Сомик-кукушка",
            "Сом Солдатова",
            "Сом Суруби",
            "Сом электрический",
            "Сомалийская рыба-бабочка",
            "Сомик леопардовый",
            "Сомик американский",
            "Сомик голубой",
            "Сомик желтый",
            "Сомик канальный",
            "Сомик оливковый",
            "Сомик черный",
            "Сом-плоскоголовик",
            "Спинорог голубой",
            "Спинорог позолоченный",
            "Спинорог бело-зеленый",
            "Спинорог голубоперый",
            "Спинорог желтомордый",
            "Спинорог заплаточный",
            "Спинорог золотоплавниковый",
            "Спинорог краснозубый",
            "Спинорог крупнопятнистый",
            "Спинорог оранжевополосый",
            "Спинорог Пикассо",
            "Спинорог расписной",
            "Спинорог розовохвостый",
            "Спинорог точечный",
            "Сплэйк",
            "Старая покрышка",
            "Стерлядь",
            "Стерлядь Сибирская",
            "Стигматохромис вуди",
            "Странствующий группер",
            "Стройный группер",
            "Стромбус волнистый",
            "Стромбус королевский",
            "Судак",
            "Судак канадский",
            "Сфирена мелкочешуйная",
            "Таедо",
            "Таймень",
            "Тамбаку",
            "Тарань",
            "Тарпон атлантический",
            "Тартаруга",
            "Тасманский краб",
            "Тасманский пескарь",
            "Тасманский рак",
            "Тегу",
            "Темно-бурый луциан",
            "Терпуг бурый",
            "Терпуг одноперый",
            "Терпуг Стеллера",
            "Тигровая рыба нильская",
            "Тигровая рыба танзанийская",
            "Тилозур красноморский",
            "Тиляпия галилейская",
            "Тиляпия Зилля",
            "Тиляпия нильская",
            "Тиляпия красногрудая",
            "Тиляпия мозамбикская",
            "Тифобия",
            "Тихоокеанская минога",
            "Тихоокеанская навага",
            "Тихоокеанская песчанка",
            "Толстолобик",
            "Томатный группер",
            "Тракакса",
            "Трахинот большой",
            "Трахинот Кеннеди",
            "Трахинот круглый",
            "Трофеус звездчатый",
            "Тукунаре",
            "Тунец индо-тихоокеанский",
            "Тунец макрелевый",
            "Тунец малый",
            "Тунец скумбриевидный",
            "Тунец южный",
            "Тонкохвостый налим",
            "Тонна гигантская",
            "Тонна ленточная",
            "Топь",
            "Травяной краб",
            "Треска атлантическая",
            "Тригла желтая",
            "Троегуб",
            "Тугун",
            "Тунец полосатый",
            "Тюрбо",
            "Уару",
            "Убанги",
            "Угольная рыба",
            "Угорь",
            "Угорь короткоребристый",
            "Угорь собачий",
            "Угорь электрический",
            "Удильщик Коммерсона",
            "Узо-угай",
            "Уклейка",
            "Украинская минога",
            "Улитка",
            "Усач",
            "Усач Валецкого",
            "Усач днепровский",
            "Усач Итальянский",
            "Уссурийская востробрюшка",
            "Уссурийская касатка",
            "Устрица",
            "Устрица гигантская",
            "Фахака",
            "Фея перламутровая",
            "Фикус изящный",
            "Флейторыл",
            "Финвал",
            "Финта",
            "Форель золотая",
            "Форель мраморная",
            "Форель тигровая",
            "Фромия элегантная",
            "Фундулюс",
            "Хапаку",
            "Хараки",
            "Хариус",
            "Хариус байкальский белый",
            "Хариус байкальский черный",
            "Хариус камчатский",
            "Хариус Сибирский",
            "Хвостокол американский",
            "Хвостокол бахромчатый",
            "Хвостокол Мацубары",
            "Хвостокол широкохвостый",
            "Хемиодопсис",
            "Хемихромис-красавец",
            "Химера европейская",
            "Хирург белогрудый",
            "Хирург желтоплавничный",
            "Хирург флаговый",
            "Храмуля",
            "Хризиптера сине-желтая",
            "Цапатеро",
            "Цапатеро-чакета",
            "Цитарина обыкновенная",
            "Цихлазома мезонаута",
            "Цихлида гигантская",
            "Цихлида Ливингстона",
            "Цихлида тупорылая",
            "Цихлида-дельфин",
            "Цихлида-колибри",
            "Чавыча",
            "Чавыча южноамериканская",
            "Чебак",
            "Черепаха",
            "Черепаха зеленая",
            "Черепаха саванная",
            "Черна бурополосая",
            "Черноморская кумжа",
            "Черноморская сельдь",
            "Черноморская шемая",
            "Чернохвостый луциан",
            "Черный амур",
            "Черный краппи",
            "Черный Лещ",
            "Черный макалор",
            "Черный марлин",
            "Четырехугольный волосатый краб",
            "Чехонь",
            "Чилийская пеламида",
            "Чилим",
            "Чир",
            "Чоп",
            "Чукучан",
            "Шабути",
            "Шамбардия Валберга",
            "Шантарская микижа",
            "Шашень",
            "Шильб полосатый",
            "Шемая",
            "Шип",
            "Широколобка красная",
            "Широколобка темная",
            "Шортбилл",
            "Шпрот европейский",
            "Шпрот танганьикский",
            "Щука",
            "Щука красноперая",
            "Щука травяная",
            "Щука черная",
            "Щука-Маскинонг",
            "Щучка Хьюжета",
            "Элагат",
            "Этелис королевский",
            "Этмоптерус серый",
            "Этмоптерус Шульца",
            "Южная мальма",
            "Южная путассу",
            "Ябби",
            "Язь",
            "Якутский голец",
            "Якутский карась",
            "Якутский осетр",
            "Ямабуки Огон",
            "Японская макрель",
            "Японский анчоус",
            "Японский мохнаторукий краб",
            "Ящерица каймановая",
            "Ящероголов красный",
            "Аба-аба ",
            "Акула-домовой ",
            "Акула-квагга ",
            "Акула большеротая ",
            "Акула гладкозубая ",
            "Акула губастая ",
            "Акула исландская ",
            "Акула китовая альбинос ",
            "Акула копьезубая ",
            "Акула коромандельская ",
            "Акула мозамбикская бычья ",
            "Акула Мицукури ",
            "Акула-нянька короткохвостая ",
            "Акула песчаная ",
            "Акула-свинья ",
            "Акула острозубая ",
            "Акула плащеносная ",
            "Акула светлохвостая ",
            "Акула светящаяся ",
            "Акула сигарная ",
            "Акула скульптурная ",
            "Акула черная ",
            "Акула шершавая ",
            "Акула эполетовая ",
            "Акулеола черная ",
            "Алепизавр ",
            "Амия ",
            "Антимора клюворылая ",
            "Асаги ",
            "Афалина ",
            "Багре хигучи ",
            "Бельдюга Андрияшева ",
            "Бэрардиус Бэрда ",
            "Велифер ",
            "Вьюн амурский ",
            "Галаксия чилийская ",
            "Гигантская тридакна ",
            "Голец белый ",
            "Голец дальнеозерский ",
            "Голец чукотский ",
            "Голец узонский ",
            "Горгасия красноморская ",
            "Граммистес шестиполосый ",
            "Группер белоокаймленный ",
            "Группер желто-синий ",
            "Группер индоокеанский малоглазый ",
            "Групер Малабарский ",
            "Губка-лира ",
            "Дорадо золотой ",
            "Жемчужная рыба ",
            "Кайман широкомордый ",
            "Калкан черноморский ",
            "Камбала двухцветная ",
            "Каранкс бронзовый ",
            "Каранкс Гебера ",
            "Катран вануатский ",
            "Кашалот-альбинос ",
            "Кижуч озерный ",
            "Кинжалозуб ",
            "Кит горбатый альбинос ",
            "Кит гренландский ",
            "Кит северный гладкий ",
            "Кит синий альбинос ",
            "Кит южный гладкий ",
            "Кланкулюс ",
            "Клюворыл Шепарда ",
            "Конус березовый ",
            "Конус Мильн-Эдвардса ",
            "Конус мраморный ",
            "Королева Ньяса ",
            "Королева Танганьики ",
            "Косатка малая ",
            "Косаткодельфин ",
            "Костерь ",
            "Краб-йети ",
            "Кракен ",
            "Лазианциструс ",
            "Линофрина индийская ",
            "Лихия ",
            "Макропинна ",
            "Макрурус вооруженный ",
            "Маллисквама ",
            "Манта рифовая ",
            "Матамата ",
            "Мегалодон ",
            "Менхэден бразильский ",
            "Мерценария Стимпсона ",
            "Мешкорот ",
            "Минога сибирская ",
            "Морская свинья бесперая ",
            "Морская свинья обыкновенная ",
            "Морская очковая свинья ",
            "Морской монах ",
            "Мурена европейская ",
            "Нарвал ",
            "Носорог пятнистый ",
            "Оксимонокант длиннорылый ",
            "Омуль баргузинский ",
            "Оринокский крокодил ",
            "Осетр адриатический ",
            "Осетр белый ",
            "Осетр тихоокеанский ",
            "Осьминог Думбо ",
            "Павлиний окунь королевский ",
            "Пайара ",
            "Палтус американский ",
            "Пилонос австралийский ",
            "Пилонос японский ",
            "Пиранья крапчатая ",
            "Пирарара ",
            "Плавун южный ",
            "Плиотрема ",
            "Принцесса Бурунди ",
            "Полосатик Омуры ",
            "Пузанок северокаспийский ",
            "Ремнезуб Блэнвиля ",
            "Ремнезуб командорский ",
            "Ремнезуб перуанский ",
            "Рыба-кабан трехполосая ",
            "Рыба-капля ",
            "Рыба-луна короткая ",
            "Рыба-луна овальная ",
            "Рыба-сабля ",
            "Рыба-тряпка ",
            "Саблезуб ",
            "Сарпа ",
            "Сельдь атлантическая ",
            "Сельдь волжская ",
            "Сельдь тихоокеанская ",
            "Сельдь чёско-печорская ",
            "Сельдяной король ",
            "Семапрохилодус ",
            "Синодонтис вуалевый ",
            "Скат акулохвостый ",
            "Скат гладкий ",
            "Скат-кукушка ",
            "Скат-орляк изысканный ",
            "Сом танганьикский ",
            "Сом ширентис ",
            "Сферомия пятнистая ",
            "Тауматихт Акселя ",
            "Тигровая рыба обыкновенная ",
            "Тифобия ",
            "Угорь собачий ",
            "Удильщик Джонсона ",
            "Удильщик Коммерсона ",
            "Утконос ",
            "Утсури ",
            "Форель апачей ",
            "Форель Бива ",
            "Форель Дональдсона ",
            "Форель остроголовая ",
            "Хвостокол кольчатый ",
            "Хендфиш ",
            "Хирург-Ахиллес ",
            "Целакант ",
            "Центрина Австралийская ",
            "Черный малакост ",
            "Черный нож ",
            "Чешуеед ",
            "Чешуйчатник ",
            "Шипощек длинноперый ",
            "Эолидия ",
            "Эферия эллиптическая ",
            "Яго Гаррика ",
            "Японский краб-стригун "});
            this.comboBox2.Location = new System.Drawing.Point(226, 35);
            this.comboBox2.Name = "comboBox2";
            this.comboBox2.Size = new System.Drawing.Size(220, 25);
            this.comboBox2.TabIndex = 1;
            // 
            // comboBox1
            // 
            this.comboBox1.FormattingEnabled = true;
            this.comboBox1.Items.AddRange(new object[] {
            "*",
            "Абрамитес мраморный",
            "Австралийский анчоус",
            "Австралийский колючепер",
            "Австралийский шишечник",
            "Адамуссиус",
            "Адский вампир",
            "Азиатская зубатка",
            "Акара голубовато-пятнистая",
            "Акарихтис Хекеля",
            "Алект вымпельный",
            "Акула",
            "Акула американская кунья",
            "Акула большеносая",
            "Акула гладкозубая",
            "Акула мадагаскарская",
            "Акула пелагическая лисья",
            "Акула пилозубая",
            "Акула темная",
            "Акула шелковая",
            "Акула-Небрия",
            "Акула-нянька короткохвостая",
            "Акула-собака",
            "Акула азиатская кунья",
            "Акула белая",
            "Акула белоглазая",
            "Акула белоперая",
            "Акула галапагосская",
            "Акула гигантская",
            "Акула гренландская",
            "Акула длиннокрылая",
            "Акула звездчатошипая",
            "Акула зебровая",
            "Акула индонезийская",
            "Акула карибская длиннорылая",
            "Акулка карликовая",
            "Акула китовая",
            "Акула мальгашская",
            "Акула мелкозубая",
            "Акула ночная",
            "Акула острозубая песчаная",
            "Акула Оустона",
            "Акула пепельная",
            "Акула плоскоголовая",
            "Акула рифовая",
            "Акула Сейла",
            "Акула свиноглазая",
            "Акула серо-бурая",
            "Акула серо-голубая",
            "Акула суповая",
            "Акула темноперая",
            "Акула тигровая",
            "Акула узкозубая",
            "Акула флоридская",
            "Акула черноперая",
            "Акула шестижаберная",
            "Акула-бык",
            "Акула-лисица",
            "Акула-молот обыкновенная",
            "Акула-нянька усатая",
            "Акула японская бычья",
            "Алеста",
            "Альбула",
            "Ампуллярия",
            "Американский угорь",
            "Амфихт",
            "Амурская Щука",
            "Амурский Осетр",
            "Амурский Сиг",
            "Анаконда",
            "Ангел лирохвостый",
            "Ангел черноплавничный",
            "Апистограммова факельная",
            "Апсил зубатый",
            "Аравана серебристая",
            "Аравана черная",
            "Арапаима",
            "Аристохромис Кристи",
            "Аротрон белоточечный",
            "Аррип большой",
            "Аррип малый",
            "Аспатария марнои",
            "Аспатария пифлоидная",
            "Астронотус глаздчатый",
            "Атлантический Осетр",
            "Аротрон колючий",
            "Архитеутис",
            "Аулонокара Бенша",
            "Аулонокара Ньяса",
            "Аухеногланис",
            "Ауха",
            "Бабочка малавийская",
            "Багре гури",
            "Багре негро",
            "Байкальский осетр",
            "Барабулька",
            "Барамунди",
            "Барракуда",
            "Барракуда тупорылая",
            "Башир",
            "Баяд",
            "Белоглазка",
            "Белуга",
            "Белуга черноморская",
            "Белуха",
            "Бельдюга восточная",
            "Белый амур",
            "Берикс австралийский",
            "Берш",
            "Бестер",
            "Биара",
            "Бикуда",
            "Бисса",
            "Болотная черепаха",
            "Большая сериола",
            "Большеротый окунь",
            "Большой каранкс",
            "Бонито",
            "Бородавчатка",
            "Бородавчатка красноморская",
            "Бронзовая акула",
            "Бротула многоусая",
            "Брызгун крупнопятнистый",
            "Букцинум",
            "Буртония Фоаи",
            "Бутылконос плоскоголовый",
            "Бутылконос северный",
            "Буффало большеротый",
            "Буффало малоротый",
            "Буффало черный",
            "Быстрянка",
            "Бычеглаз-хамрур",
            "Бычерыл американский",
            "Бычок",
            "Бычок-кнут",
            "Бычок краснозубый",
            "Бычок-цуцик",
            "Валаамка",
            "Валек",
            "Вариола белокаемчатая",
            "Ваху",
            "Венера воздушная",
            "Верхогляд",
            "Веслонос",
            "Владиславия",
            "Вобла",
            "Волосозуб",
            "Волютопсиус каштановый",
            "Ворчун крапчатый",
            "Восточная треска",
            "Восточносибирский хариус",
            "Вунду",
            "Вырезуб",
            "Вьюн",
            "Галаксия пятнистая",
            "Галаксия Тасманская",
            "Гаррупа-мармита",
            "Гетеротис",
            "Гигантская акула-молот",
            "Гигантский головастик",
            "Гигантский карп",
            "Гидромедуза бразильская",
            "Гимносарда",
            "Гипоплектрус",
            "Гитарный скат",
            "Глаукус",
            "Глицимерис приморский",
            "Глосса",
            "Глубинная щука",
            "Глубинный судак",
            "Голавль",
            "Голец альпийский",
            "Голец арктический",
            "Голец длинноголовый",
            "Голец-кристивомер",
            "Голец Леванидова",
            "Голец носатый",
            "Голец Таранца",
            "Голец усатый",
            "Голец Черского",
            "Голомянка",
            "Голубая акула",
            "Голубая линкия",
            "Голубой марлин",
            "Голубой тунец",
            "Голый осман",
            "Гольян Лаговского",
            "Гольян Чекановского",
            "Гонатус",
            "Горбуша",
            "Горбуша южноамериканская",
            "Горбыль",
            "Гребешок бело-розовый",
            "Гребешок исландский",
            "Гребешок коралловый",
            "Грамма королевская",
            "Гребешок лунный",
            "Гребешок раскрашенный",
            "Гребешок Свифта",
            "Гребнистый крокодил",
            "Гребешок многообразный",
            "Гринда обыкновенная",
            "Греческий сосуд",
            "Гринда короткоплавниковая",
            "Группер Квинслендский",
            "Группер красноротый",
            "Группер таувина",
            "Группер буропятнистый",
            "Группер желто-синий",
            "Группер индоокеанский малоглазый",
            "Группер крупнопятнистый",
            "Группер палевый",
            "Группер темный",
            "Группер шестиполосый",
            "Гуативера",
            "Гуачанчо",
            "Губан гребенчатый",
            "Губан колючий",
            "Губан носатый",
            "Губан пятнистый",
            "Губан радужный",
            "Густера",
            "Даватчан",
            "Даллия",
            "Дасцилл зебровидный",
            "Двухцветная пеламида",
            "Джакунда",
            "Дианема полосатохвостая",
            "Дискус зеленый",
            "Дискус Хеккеля",
            "Дистиходус шестиполосый",
            "Длиннопалый рак",
            "Длинноперый тунец",
            "Длиннорылый полурыл",
            "Долгопер средиземноморский",
            "Дорадо",
            "Дрейссена речная",
            "Дунайский пузанок",
            "Евдошка европейская",
            "Евдошка американская",
            "Единорог расписной",
            "Елец",
            "Елец-андруга",
            "Елец Сибирский",
            "Ерш",
            "Ерш носарь",
            "Ершоватка",
            "Желтокрылка",
            "Желтопёрый тунец",
            "Желтохвост",
            "Желтощек",
            "Жерех",
            "Жерех-лысач",
            "Зайцеголовый терпуг",
            "Запрора",
            "Звезда-подушка",
            "Звездочет крапчатый",
            "Зебровый хирург",
            "Зеленушка",
            "Зеленый луциан",
            "Змееголов",
            "Змеиная макрель",
            "Золотистая сериола",
            "Золотистая скорпена",
            "Золотистый линь",
            "Золотой леопард",
            "Зубатка дальневосточная",
            "Зубатка полосатая",
            "Зубатка пятнистая",
            "Зубатка синяя",
            "Зубарик обыкновенный",
            "Иглобрюх-попугайчик",
            "Идол мавританский",
            "Императорский ангел",
            "Инанга",
            "Иния",
            "Кабра-мора",
            "Кабрилья",
            "Кабуча",
            "Кайман гладколобый",
            "Кайман крокодиловый",
            "Кайман черный",
            "Калинка",
            "Каллиста короткосифонная",
            "Каллитака Адамса",
            "Каллихт",
            "Калуга",
            "Кальмар гигантский",
            "Кальмар командорский",
            "Кальмар обыкновенный",
            "Кальмар тихоокеанский",
            "Камбала двухлинейная",
            "Камбала звёздчатая",
            "Камбала зеленая",
            "Камбала кесслера",
            "Камбала морская",
            "Камнеточец",
            "Камчатский краб",
            "Каракатица лечебная",
            "Каракатица расписная",
            "Кальвус",
            "Камерония Бургинья",
            "Кампанго",
            "Каранкс черный",
            "Каранг золотой",
            "Карась золотой",
            "Карась серебряный",
            "Карась морской",
            "Карась морской чернополосый",
            "Карась-барабан",
            "Кардиум реснитчатый",
            "Карп",
            "Карп африканский",
            "Карп голый",
            "Карп зеркальный",
            "Карп индийский",
            "Картофельный группер",
            "Катран",
            "Каури-монета",
            "Кашалот",
            "Кашалот карликовый",
            "Кашорро краснохвостый",
            "Керчак-яок",
            "Кета",
            "Кефаль алмазная",
            "Кефаль-губач",
            "Кефаль-лобан",
            "Кижуч",
            "Кижуч южноамериканский",
            "Кит горбатый",
            "Кит карликовый",
            "Кит серый",
            "Кит синий",
            "Кит японский",
            "Кит бискайский",
            "Китовая акула",
            "Клоун танганьикский",
            "Клюворыл",
            "Коаро",
            "Кобия",
            "Комета",
            "Конголли",
            "Конус дворцовый",
            "Конус географический",
            "Конус письменный",
            "Конус полосатый",
            "Конус текстильный",
            "Кожистая черепаха",
            "Кокани",
            "Колоссома",
            "Колючий краб",
            "Колюшка девятииглая",
            "Колюшка трехиглая",
            "Копьеносец малый",
            "Коралловый группер",
            "Корифена малая",
            "Королевский луциан",
            "Корюшка",
            "Корюшка озерная малоротая",
            "Косатка",
            "Коелатура мозамбикская",
            "Королева Ньяса",
            "Королева Танганьики",
            "Кохаку",
            "Кошачья акула",
            "Краб вельветовый",
            "Краб королевский",
            "Краб красный мангровый",
            "Краб Мраморный",
            "Краб сине-красный",
            "Краб снежный",
            "Краб съедобный",
            "Краб малавийский голубой",
            "Краб монтивагус",
            "Краб танганьикский",
            "Краппи белый",
            "Красное бревно",
            "Красноперка",
            "Красный конгрио",
            "Красный луциан",
            "Креветка северная",
            "Крокодил Джонстона",
            "Крокодил нильский",
            "Крокодил узкорылый",
            "Крупночешуйчатый угай",
            "Крылатка-зебра",
            "Крылатка антенновая",
            "Кряжевая палия",
            "Кубера",
            "Кудрепер Форстера",
            "Кузовок-кубик",
            "Кузовок рогатый",
            "Кумжа",
            "Кумжа южноамериканская",
            "Кунджа",
            "Кутум",
            "Кэтфиш",
            "Лабеотрофеус обыкновенный",
            "Лабидохромис большой",
            "Лабидохромис Хонги",
            "Лаванда Мбуна",
            "Лабынкырская мальма",
            "Лабынкырский хариус",
            "Лабынкырский чёрт",
            "Лаврак",
            "Лаврак белый",
            "Лаврак полосатый",
            "Ламна",
            "Ледяная рыба",
            "Лемонема",
            "Ленок",
            "Ленский пескарь",
            "Ленский хариус",
            "Леопардовый группер",
            "Лепоринус зебровый",
            "Лепоринус фредерика",
            "Летрин длиннорылый",
            "Летрин небесный",
            "Лещ",
            "Лещ Восточносибирский",
            "Лещ морской белый",
            "Лещ морской кинжальный",
            "Лещ морской",
            "Лещ черный южный",
            "Ликодонт яванский",
            "Лиманда длиннорылая",
            "Лиманда желтохвостая",
            "Линь",
            "Логгерхед",
            "Лососевая акула",
            "Лосось",
            "Лосось дунайский",
            "Лосось Каспийский",
            "Лосось Кларка",
            "Лосось южноамериканский",
            "Лоцман",
            "Луварь",
            "Лудога",
            "Лудожная палия",
            "Лунник",
            "Луфарь",
            "Луциан Бохар",
            "Луциан горбатый",
            "Лягушка",
            "Лягушка нильская",
            "Лягушка роющая",
            "Лямбис подагрический",
            "Мавританский клоун",
            "Мазутный двухголов",
            "Макома широкая",
            "Макрель бразильская",
            "Макрель голубая",
            "Мако длинноплавниковый",
            "Макрель западноатлантическая",
            "Макруронус новозеландский",
            "Макрель-Кавалла",
            "Мактра китайская",
            "Мактра сахалинская",
            "Мактромерис изменчивый",
            "Малабарский хоплиас",
            "Малоглазый макрурус",
            "Малый полосатик",
            "Мальма",
            "Мангровый джек",
            "Мандаринка",
            "Манта",
            "Марлин атлантический",
            "Масляная рыба",
            "Мбамба",
            "Мбенга",
            "Меланохромис",
            "Мелания песчаная",
            "Мелкозубый пилорыл",
            "Мелкочешуйчатый краснопер",
            "Мелкочешуйчатый угай",
            "Мена пятнистая",
            "Менёк",
            "Мерланг",
            "Мероу красный",
            "Метиннис пятнистый",
            "Мидия",
            "Микижа",
            "Микижа чилийская",
            "Миксина атлантическая",
            "Милеус ленточный",
            "Милоссома килебрюхая",
            "Минтай",
            "Минога морская",
            "Минога огайская",
            "Многопёр Эндлихера",
            "Мормир бутылконосый",
            "Моллюск",
            "Монгольский краснопер",
            "Мормиропс угревидный",
            "Морская звезда красношипая",
            "Мойва",
            "Мольва",
            "Морская лисица",
            "Морская свинья Далля",
            "Морская свинья тихоокеанская",
            "Морская собачка",
            "Морской ворон",
            "Морской еж",
            "Морской орел",
            "Морской финик",
            "Морской черт",
            "Моторо",
            "Мригал",
            "Мускулус",
            "Муксун",
            "Мурджан",
            "Мурена гигантская",
            "Мурена перечная",
            "Муреная ячеистая",
            "Мурена европейская",
            "Мурена желторотая",
            "Мурена ленточная",
            "Мурена-зебра",
            "Мутела",
            "Мухтельский карась",
            "Налим",
            "Налим средиземноморский",
            "Нанностом Бекфорда",
            "Неалот",
            "Нейва",
            "Нельма",
            "Необерингиус Фрилея",
            "Нереис",
            "Нерка",
            "Нерка карликовая",
            "Нерпа байкальская",
            "Нильский окунь",
            "Нимбохромис полистигма",
            "Нодулария боеми",
            "Носорог безрогий",
            "Носорог однорогий",
            "Новозеландская мерлуза",
            "Носатая энгидрина",
            "Обыкновенный краб-стригун",
            "Озерная форель",
            "Озерный гольян",
            "Окунь",
            "Окунь алеутский",
            "Окунь большеглазый",
            "Окунь вилохвостый",
            "Окунь гладкий",
            "Окунь танганьикский",
            "Окунь золотой",
            "Окунь малый",
            "Окунь северный морской",
            "Окунь каменный",
            "Окунь красноглазый",
            "Окунь малоротый",
            "Окунь морской золотистый",
            "Окунь морской норвежский",
            "Окунь песчаный",
            "Окунь прибрежный",
            "Окунь пятнистый",
            "Окунь ушастый",
            "Окунь-клювач",
            "Окунь-пират",
            "Омар голубой",
            "Омар европейский",
            "Омар норвежский",
            "Омуль",
            "Омуль Байкальский",
            "Омуль маломорский",
            "Омуль посольский",
            "Омуль северобайкальский",
            "Омуль селенгинский",
            "Омуль чивыркуйский",
            "Оникия",
            "Ореохромис Каронга",
            "Оренжи Огон",
            "Орфа",
            "Ореховидка тонкая",
            "Осетр",
            "Осетр тупорылый",
            "Осетр Восточносибирский",
            "Острорылый крокодил",
            "Острорылый ленок",
            "Осьминог обыкновенный",
            "Осьминог семирукий",
            "Офиура полосатая",
            "Офтальмотиляпия носатая",
            "Павлиний группер",
            "Павлиний окунь-бабочка",
            "Павлиний окунь ленточный",
            "Пагелл красный",
            "Пагр красный",
            "Пака",
            "Палия",
            "Палия американская",
            "Палия южноамериканская",
            "Палтус атлантический",
            "Палтус Белокорый",
            "Палтус синекорый",
            "Палтус стрелозубый",
            "Пальмовый вор",
            "Панцирник длиннорылый",
            "Панцирник миссисипский",
            "Парусник",
            "Патагонский гребешок",
            "Патагонский клыкач",
            "Патагонский лобстер",
            "Пеламида атлантическая",
            "Пеленгас",
            "Пелядь",
            "Пенжинский омуль",
            "Переславская ряпушка",
            "Перечный слизняк",
            "Перка",
            "Перонидия жилковатая",
            "Персидский осетр",
            "Перуанский анчоус",
            "Перуанская макрель",
            "Перуанская сардина",
            "Перуанская сериолелла",
            "Перуанская ставрида",
            "Пескарь",
            "Пестрый конь",
            "Пестрый толстолобик",
            "Петушок",
            "Пигоплит",
            "Пикша",
            "Пинагор",
            "Пираиба",
            "Пиракатинга",
            "Пиранья вымпельная",
            "Пиранья краснобрюхая",
            "Пиранья обыкновенная",
            "Пиранья ромбовидная",
            "Пиранья стройная",
            "Пирапитинга",
            "Пирапутанга",
            "Пираруку",
            "Пиратский клад",
            "Платакс-нетопырь",
            "Плоскоголов бахромчатый",
            "Платинум Огон",
            "Плоскоголов пятнистый",
            "Плотва",
            "Подкаменщик",
            "Подлещик",
            "Подуст",
            "Полиптер",
            "Поллак",
            "Поллимир Исидора",
            "Полосатая камбала",
            "Полосатик Брайда",
            "Полосатик Идена",
            "Полосатик карликовый",
            "Полосатик южный",
            "Полосатый марлин",
            "Полярная акула",
            "Помакант рябой",
            "Попока",
            "Пресноводный краб",
            "Принцесса Бурунди",
            "Протоптер бурый",
            "Протоптер малый",
            "Приморский гребешок",
            "Промикропс",
            "Протоптер мраморный",
            "Прудовик",
            "Псевдотрофеус Демасони",
            "Птеригоплихт парчовый",
            "Пузанок",
            "Пустая бочка",
            "Путассу северная",
            "Пыжьян",
            "Пятиугольный волосатый краб",
            "Пятнистая озерная лягушка",
            "Пятнистый воббегонг",
            "Пятнистый рак",
            "Пятнистый сладкогуб",
            "Радужная вариола",
            "Радужная форель",
            "Рак",
            "Рак красный флоридский",
            "Рак сигнальный",
            "Рапана",
            "Рапана венозная",
            "Рваный сапог",
            "Ремнезуб атлантический",
            "Ремнезуб Грея",
            "Ремнезуб Блэнвиля",
            "Рипус",
            "Робало",
            "Рогатка",
            "Розовый луциан",
            "Ротан",
            "Ручьевая форель",
            "Рыба лира",
            "Рыба меч",
            "Рыба-бекас",
            "Рыба-белка",
            "Рыба-еж длинношипая",
            "Рыба-лиса",
            "Рыба-луна",
            "Рыба-лягушка",
            "Рыба-Наполеон",
            "Рыба-ремень",
            "Рыбальдо",
            "Рыбец",
            "Ряпушка",
            "Сазан",
            "Сайда",
            "Сайка",
            "Сайра атлантическая",
            "Саратога",
            "Сарган",
            "Сарган крокодиловый",
            "Сардина танганьикская",
            "Сардина европейская",
            "Сахалинская лиманда",
            "Сахалинский осетр",
            "Свинья аргентинская",
            "Свистулька голубопятнистая",
            "Сева",
            "Севанская форель",
            "Северный клювач",
            "Севрюга",
            "Сейвал",
            "Селар",
            "Сельдь американская",
            "Сельдь Каспийская",
            "Семга",
            "Семга камчатская",
            "Семутунду",
            "Сердцевидка съедобная",
            "Сердеронг чернопятнистый",
            "Серое бревно",
            "Серрипес замечательный",
            "Серцевидка",
            "Сиб.голец-усач",
            "Сибирская ряпушка",
            "Сибирский подкаменщик",
            "Сиг",
            "Сиг-востряк",
            "Сиг-Xадары",
            "Сиган звездчатый",
            "Сиган струйчатый",
            "Сиган яванский",
            "Сима",
            "Сима южноамериканская",
            "Синекольчатый осьминог",
            "Синеплавниковый каранкс",
            "Синеполосый луциан",
            "Синец",
            "Скалозуб бурый",
            "Скватина американская",
            "Скалярия леопольда",
            "Скар двухцветный",
            "Скар рубиновый",
            "Скар широколобый",
            "Скат",
            "Скат пятнистый",
            "Скат-орляк белоточечный",
            "Скат-орляк изысканный",
            "Скат акулий",
            "Скат колючий",
            "Скат мозаичный",
            "Скат Йенсена",
            "Скат короткохвостый",
            "Скат круглый",
            "Скат лучевой",
            "Скат Монтегю",
            "Скат полярный",
            "Скат тэниура лимма",
            "Скат-орляк пятнистый",
            "Скат-торпедо электрический",
            "Скат-орляк австралийский",
            "Сладкогуб гигантский",
            "Скорпенопсис дьявольский",
            "Скрипун",
            "Скумбрия атлантическая",
            "Снэппер низкотелый",
            "Снэппер нитеперый",
            "Собачка речная",
            "Солидус",
            "Солнечник обыкновенный",
            "Солнечник синежаберный",
            "Сом",
            "Сом Амурский",
            "Сом жирафовый",
            "Сом малавийский",
            "Сом мраморный",
            "Сом танганьикский",
            "Сом ширентис",
            "Сомик-кукушка",
            "Сом Солдатова",
            "Сом Суруби",
            "Сом электрический",
            "Сомалийская рыба-бабочка",
            "Сомик леопардовый",
            "Сомик американский",
            "Сомик голубой",
            "Сомик желтый",
            "Сомик канальный",
            "Сомик оливковый",
            "Сомик черный",
            "Сом-плоскоголовик",
            "Спинорог голубой",
            "Спинорог позолоченный",
            "Спинорог бело-зеленый",
            "Спинорог голубоперый",
            "Спинорог желтомордый",
            "Спинорог заплаточный",
            "Спинорог золотоплавниковый",
            "Спинорог краснозубый",
            "Спинорог крупнопятнистый",
            "Спинорог оранжевополосый",
            "Спинорог Пикассо",
            "Спинорог расписной",
            "Спинорог розовохвостый",
            "Спинорог точечный",
            "Сплэйк",
            "Старая покрышка",
            "Стерлядь",
            "Стерлядь Сибирская",
            "Стигматохромис вуди",
            "Странствующий группер",
            "Стройный группер",
            "Стромбус волнистый",
            "Стромбус королевский",
            "Судак",
            "Судак канадский",
            "Сфирена мелкочешуйная",
            "Таедо",
            "Таймень",
            "Тамбаку",
            "Тарань",
            "Тарпон атлантический",
            "Тартаруга",
            "Тасманский краб",
            "Тасманский пескарь",
            "Тасманский рак",
            "Тегу",
            "Темно-бурый луциан",
            "Терпуг бурый",
            "Терпуг одноперый",
            "Терпуг Стеллера",
            "Тигровая рыба нильская",
            "Тигровая рыба танзанийская",
            "Тилозур красноморский",
            "Тиляпия галилейская",
            "Тиляпия Зилля",
            "Тиляпия нильская",
            "Тиляпия красногрудая",
            "Тиляпия мозамбикская",
            "Тифобия",
            "Тихоокеанская минога",
            "Тихоокеанская навага",
            "Тихоокеанская песчанка",
            "Толстолобик",
            "Томатный группер",
            "Тракакса",
            "Трахинот большой",
            "Трахинот Кеннеди",
            "Трахинот круглый",
            "Трофеус звездчатый",
            "Тукунаре",
            "Тунец индо-тихоокеанский",
            "Тунец макрелевый",
            "Тунец малый",
            "Тунец скумбриевидный",
            "Тунец южный",
            "Тонкохвостый налим",
            "Тонна гигантская",
            "Тонна ленточная",
            "Топь",
            "Травяной краб",
            "Треска атлантическая",
            "Тригла желтая",
            "Троегуб",
            "Тугун",
            "Тунец полосатый",
            "Тюрбо",
            "Уару",
            "Убанги",
            "Угольная рыба",
            "Угорь",
            "Угорь короткоребристый",
            "Угорь собачий",
            "Угорь электрический",
            "Удильщик Коммерсона",
            "Узо-угай",
            "Уклейка",
            "Украинская минога",
            "Улитка",
            "Усач",
            "Усач Валецкого",
            "Усач днепровский",
            "Усач Итальянский",
            "Уссурийская востробрюшка",
            "Уссурийская касатка",
            "Устрица",
            "Устрица гигантская",
            "Фахака",
            "Фея перламутровая",
            "Фикус изящный",
            "Флейторыл",
            "Финвал",
            "Финта",
            "Форель золотая",
            "Форель мраморная",
            "Форель тигровая",
            "Фромия элегантная",
            "Фундулюс",
            "Хапаку",
            "Хараки",
            "Хариус",
            "Хариус байкальский белый",
            "Хариус байкальский черный",
            "Хариус камчатский",
            "Хариус Сибирский",
            "Хвостокол американский",
            "Хвостокол бахромчатый",
            "Хвостокол Мацубары",
            "Хвостокол широкохвостый",
            "Хемиодопсис",
            "Хемихромис-красавец",
            "Химера европейская",
            "Хирург белогрудый",
            "Хирург желтоплавничный",
            "Хирург флаговый",
            "Храмуля",
            "Хризиптера сине-желтая",
            "Цапатеро",
            "Цапатеро-чакета",
            "Цитарина обыкновенная",
            "Цихлазома мезонаута",
            "Цихлида гигантская",
            "Цихлида Ливингстона",
            "Цихлида тупорылая",
            "Цихлида-дельфин",
            "Цихлида-колибри",
            "Чавыча",
            "Чавыча южноамериканская",
            "Чебак",
            "Черепаха",
            "Черепаха зеленая",
            "Черепаха саванная",
            "Черна бурополосая",
            "Черноморская кумжа",
            "Черноморская сельдь",
            "Черноморская шемая",
            "Чернохвостый луциан",
            "Черный амур",
            "Черный краппи",
            "Черный Лещ",
            "Черный макалор",
            "Черный марлин",
            "Четырехугольный волосатый краб",
            "Чехонь",
            "Чилийская пеламида",
            "Чилим",
            "Чир",
            "Чоп",
            "Чукучан",
            "Шабути",
            "Шамбардия Валберга",
            "Шантарская микижа",
            "Шашень",
            "Шильб полосатый",
            "Шемая",
            "Шип",
            "Широколобка красная",
            "Широколобка темная",
            "Шортбилл",
            "Шпрот европейский",
            "Шпрот танганьикский",
            "Щука",
            "Щука красноперая",
            "Щука травяная",
            "Щука черная",
            "Щука-Маскинонг",
            "Щучка Хьюжета",
            "Элагат",
            "Этелис королевский",
            "Этмоптерус серый",
            "Этмоптерус Шульца",
            "Южная мальма",
            "Южная путассу",
            "Ябби",
            "Язь",
            "Якутский голец",
            "Якутский карась",
            "Якутский осетр",
            "Ямабуки Огон",
            "Японская макрель",
            "Японский анчоус",
            "Японский мохнаторукий краб",
            "Ящерица каймановая",
            "Ящероголов красный",
            "Аба-аба ",
            "Акула-домовой ",
            "Акула-квагга ",
            "Акула большеротая ",
            "Акула гладкозубая ",
            "Акула губастая ",
            "Акула исландская ",
            "Акула китовая альбинос ",
            "Акула копьезубая ",
            "Акула коромандельская ",
            "Акула мозамбикская бычья ",
            "Акула Мицукури ",
            "Акула-нянька короткохвостая ",
            "Акула песчаная ",
            "Акула-свинья ",
            "Акула острозубая ",
            "Акула плащеносная ",
            "Акула светлохвостая ",
            "Акула светящаяся ",
            "Акула сигарная ",
            "Акула скульптурная ",
            "Акула черная ",
            "Акула шершавая ",
            "Акула эполетовая ",
            "Акулеола черная ",
            "Алепизавр ",
            "Амия ",
            "Антимора клюворылая ",
            "Асаги ",
            "Афалина ",
            "Багре хигучи ",
            "Бельдюга Андрияшева ",
            "Бэрардиус Бэрда ",
            "Велифер ",
            "Вьюн амурский ",
            "Галаксия чилийская ",
            "Гигантская тридакна ",
            "Голец белый ",
            "Голец дальнеозерский ",
            "Голец чукотский ",
            "Голец узонский ",
            "Горгасия красноморская ",
            "Граммистес шестиполосый ",
            "Группер белоокаймленный ",
            "Группер желто-синий ",
            "Группер индоокеанский малоглазый ",
            "Групер Малабарский ",
            "Губка-лира ",
            "Дорадо золотой ",
            "Жемчужная рыба ",
            "Кайман широкомордый ",
            "Калкан черноморский ",
            "Камбала двухцветная ",
            "Каранкс бронзовый ",
            "Каранкс Гебера ",
            "Катран вануатский ",
            "Кашалот-альбинос ",
            "Кижуч озерный ",
            "Кинжалозуб ",
            "Кит горбатый альбинос ",
            "Кит гренландский ",
            "Кит северный гладкий ",
            "Кит синий альбинос ",
            "Кит южный гладкий ",
            "Кланкулюс ",
            "Клюворыл Шепарда ",
            "Конус березовый ",
            "Конус Мильн-Эдвардса ",
            "Конус мраморный ",
            "Королева Ньяса ",
            "Королева Танганьики ",
            "Косатка малая ",
            "Косаткодельфин ",
            "Костерь ",
            "Краб-йети ",
            "Кракен ",
            "Лазианциструс ",
            "Линофрина индийская ",
            "Лихия ",
            "Макропинна ",
            "Макрурус вооруженный ",
            "Маллисквама ",
            "Манта рифовая ",
            "Матамата ",
            "Мегалодон ",
            "Менхэден бразильский ",
            "Мерценария Стимпсона ",
            "Мешкорот ",
            "Минога сибирская ",
            "Морская свинья бесперая ",
            "Морская свинья обыкновенная ",
            "Морская очковая свинья ",
            "Морской монах ",
            "Мурена европейская ",
            "Нарвал ",
            "Носорог пятнистый ",
            "Оксимонокант длиннорылый ",
            "Омуль баргузинский ",
            "Оринокский крокодил ",
            "Осетр адриатический ",
            "Осетр белый ",
            "Осетр тихоокеанский ",
            "Осьминог Думбо ",
            "Павлиний окунь королевский ",
            "Пайара ",
            "Палтус американский ",
            "Пилонос австралийский ",
            "Пилонос японский ",
            "Пиранья крапчатая ",
            "Пирарара ",
            "Плавун южный ",
            "Плиотрема ",
            "Принцесса Бурунди ",
            "Полосатик Омуры ",
            "Пузанок северокаспийский ",
            "Ремнезуб Блэнвиля ",
            "Ремнезуб командорский ",
            "Ремнезуб перуанский ",
            "Рыба-кабан трехполосая ",
            "Рыба-капля ",
            "Рыба-луна короткая ",
            "Рыба-луна овальная ",
            "Рыба-сабля ",
            "Рыба-тряпка ",
            "Саблезуб ",
            "Сарпа ",
            "Сельдь атлантическая ",
            "Сельдь волжская ",
            "Сельдь тихоокеанская ",
            "Сельдь чёско-печорская ",
            "Сельдяной король ",
            "Семапрохилодус ",
            "Синодонтис вуалевый ",
            "Скат акулохвостый ",
            "Скат гладкий ",
            "Скат-кукушка ",
            "Скат-орляк изысканный ",
            "Сом танганьикский ",
            "Сом ширентис ",
            "Сферомия пятнистая ",
            "Тауматихт Акселя ",
            "Тигровая рыба обыкновенная ",
            "Тифобия ",
            "Угорь собачий ",
            "Удильщик Джонсона ",
            "Удильщик Коммерсона ",
            "Утконос ",
            "Утсури ",
            "Форель апачей ",
            "Форель Бива ",
            "Форель Дональдсона ",
            "Форель остроголовая ",
            "Хвостокол кольчатый ",
            "Хендфиш ",
            "Хирург-Ахиллес ",
            "Целакант ",
            "Центрина Австралийская ",
            "Черный малакост ",
            "Черный нож ",
            "Чешуеед ",
            "Чешуйчатник ",
            "Шипощек длинноперый ",
            "Эолидия ",
            "Эферия эллиптическая ",
            "Яго Гаррика ",
            "Японский краб-стригун "});
            this.comboBox1.Location = new System.Drawing.Point(6, 35);
            this.comboBox1.Name = "comboBox1";
            this.comboBox1.Size = new System.Drawing.Size(220, 25);
            this.comboBox1.TabIndex = 0;
            // 
            // tabPage2
            // 
            this.tabPage2.Location = new System.Drawing.Point(4, 26);
            this.tabPage2.Name = "tabPage2";
            this.tabPage2.Padding = new System.Windows.Forms.Padding(3);
            this.tabPage2.Size = new System.Drawing.Size(452, 285);
            this.tabPage2.TabIndex = 1;
            this.tabPage2.Text = "------";
            this.tabPage2.UseVisualStyleBackColor = true;
            // 
            // Form1
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(7F, 17F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.BackColor = System.Drawing.Color.LightSteelBlue;
            this.ClientSize = new System.Drawing.Size(472, 717);
            this.Controls.Add(this.tabControl1);
            this.Controls.Add(this.statusStrip1);
            this.Controls.Add(this.checkBox1);
            this.Controls.Add(this.button3);
            this.Controls.Add(this.button2);
            this.Controls.Add(this.button1);
            this.Controls.Add(this.listBox1);
            this.Controls.Add(this.menuStrip1);
            this.DoubleBuffered = true;
            this.FormBorderStyle = System.Windows.Forms.FormBorderStyle.FixedSingle;
            this.Icon = ((System.Drawing.Icon)(resources.GetObject("$this.Icon")));
            this.KeyPreview = true;
            this.MaximizeBox = false;
            this.Name = "Form1";
            this.StartPosition = System.Windows.Forms.FormStartPosition.CenterScreen;
            this.Text = "ClFIsh 1.0.3";
            this.menuStrip1.ResumeLayout(false);
            this.menuStrip1.PerformLayout();
            this.statusStrip1.ResumeLayout(false);
            this.statusStrip1.PerformLayout();
            this.tabControl1.ResumeLayout(false);
            this.tabPage1.ResumeLayout(false);
            this.tabPage1.PerformLayout();
            ((System.ComponentModel.ISupportInitialize)(this.pictureBox1)).EndInit();
            this.ResumeLayout(false);
            this.PerformLayout();

        }

        #endregion

        private ListBox listBox1;
        private Button button1;
        private Button button2;
        private System.Windows.Forms.Timer mainTimer;
        private MenuStrip menuStrip1;
        private ToolStripMenuItem настрокиToolStripMenuItem;
        private ToolStripMenuItem очиститьЛогToolStripMenuItem;
        private Button button3;
        private CheckBox checkBox1;
        private System.Windows.Forms.Timer chTimer;
        private StatusStrip statusStrip1;
        private ToolStripStatusLabel toolStripStatusLabel1;
        private ToolStripStatusLabel toolStripStatusLabel3;
        private ToolStripStatusLabel toolStripStatusLabel2;
        private ToolStripStatusLabel toolStripStatusLabel4;
        private ToolStripStatusLabel toolStripStatusLabel5;
        private ToolStripStatusLabel toolStripStatusLabel6;
        private ToolStripStatusLabel toolStripStatusLabel7;
        private TabControl tabControl1;
        private TabPage tabPage1;
        private ListBox listBox3;
        private ListBox listBox2;
        private Label label2;
        private Label label1;
        private ComboBox comboBox2;
        private ComboBox comboBox1;
        private TabPage tabPage2;
        private TextBox textBox1;
        private CheckBox checkBox2;
        private Button button4;
        private ListBox lstTargets;
        private PictureBox pictureBox1;
    }
}